### ISSUE TITLE
Connectivity via USB

### ISSUE THREAD

**Issue by farsonic** [malosaa/Growatt_Shine-S_HASS_Mod#1]
Is the intention of this code to allow direct connection via USB into the Inverter and then present this using ESPHOME? I've flashed an ESP32 but not sure if this is supposed to be connected directly?

**Comment by malosaa** [comment]
Sorry for my late response, i was very very busy.

WIth an ESP32 it should be connected directly without the pins attached, as that procedure is only for the SHINE devices to put them in flash mode.
With the SHINE-S u need to use the connector cables RX TX etc, than u can flash it without soldering.
With the SHINE-X and ESP i did not test it but it works.

If u flashed it correctly it should popup in home-assistant to be added.
My code should work for ESP, X and the S version.

What kind of inverter do you have ?

Regards
